update workflow

diff --git a/.github/workflows/hugo-ci.yaml b/.github/workflows/hugo-ci.yaml
--- a/.github/workflows/hugo-ci.yaml
+++ b/.github/workflows/hugo-ci.yaml
@@ -33,11 +33,29 @@ jobs:
           hugo-version: '0.144.2'
           extended: true
 
-      - name: Hugo Audit
+      - name: Build Hugo site for audit
         run: |
-          hugo && grep -inorE "<\!-- raw HTML omitted -->|ZgotmplZ|\[i18n\]|\(\)|(<nil>)|hahahugo" public/
+          hugo \
+           --destination "${OUTPUT_DIRECTORY}"
+           --gc \
+           --cleanDestinationDir && grep -inorE "<\!-- raw HTML omitted -->|ZgotmplZ|\[i18n\]|\(\)|(<nil>)|hahahugo" "${OUTPUT_DIRECTORY}"
+          if [ ! -s "$OUTPUT_DIRECTORY"/index.html ]; then echo "Missing output"; exit 1; fi
         env:
           HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
+          HUGO_ENVIRONMENT: production
           TZ: Europe/Stockholm
-          HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS: true
+          OUTPUT_DIRECTORY: "audit/"
           HUGO_ENABLEMISSINGTRANSLATIONPLACEHOLDERS: true
+          HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS: true
+          
+      - name: Audit Hugo site (hugo-audit.log)
+        run: |
+          if ! grep -iIrnE '<\!-- raw HTML omitted -->|ZgotmplZ|hahahugo|\[i18n\]|\(<nil>\)|\(&lt;nil&gt;\)' ${OUTPUT_DIRECTORY} >hugo-audit.log; then RET=$?; fi; if test "$RET" = "2"; then echo "not ok"; exit 1; fi
+        env:
+          OUTPUT_DIRECTORY: "audit/"
+      
+      - name: Audit Hugo site (hugo-audit.log)
+        run: |
+          if test -s hugo-audit.log; then RET2=2; { { grep -iIvE 'grep(.+(-- raw HTML omitted --|ZgotmplZ|hahahugo|\\\[i18n\\\]|\\\(<nil>\\\)|\\\(&lt;nil&gt;\\\))+)' hugo-audit.log; RET2=$?; } || true; }; if test "$RET2" != "1"; then echo "not ok"; exit 1; fi; else echo "ok"; exit 0; fi
+        env:
+          OUTPUT_DIRECTORY: "audit/"
